services:
  - type: web
    name: room-chat-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000

  - type: web
    name: room-chat-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://room-chat-api-zg95.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://room-chat-api-zg95.onrender.com
      - key: VITE_AUTH_DISABLED
        value: "true"

databases:
  - name: room_chat_db
    plan: free
